; [ppx_expect] has a bug with (include_subdirs unqualified) that Jane Street
; hasn't merged fixed for yet: https://github.com/janestreet/ppx_expect/pull/66
; Once this is fixed, I would rather use that

(library
 (name oxcaml_chess)
 (libraries chess_primitives chess_rules chess_protocols chess_engine))
